### ISSUE TITLE
Change "Acceptance rate" wording

### ISSUE THREAD

**Issue by reillyinnes** [gjcooper/samplers#31]

**Comment by gjcooper** [comment]
Hi Reilly,

Can you remind me of the details of this?

Where the current wording is displayed, and what a good alternative might be would be a nice detail to add to this issue.

**Comment by reillyinnes** [comment]
From memory, the problem was that UNSW team would not call it "acceptance" as such because it was always technically accepted, but it was like a "new particle accepted" or something like that, with the focus on the "new" or "unique" part. 

I think currently, the wording is just "Acc" next to the progress bar. I'm not sure if there are any other warnings, but i will look them up. Might have to think a little more about what would be a good switch for "Acc" in the output (which is still short and informative)

**Comment by gjcooper** [comment]
Hmm, @reillyinnes , revisiting this before the next version launch - and what about in place of **Acc** for the progress bar, instead I use **New** (and then in the documentation expand on this to explain what this refers to)

**Comment by reillyinnes** [comment]
I like this as a fix - that should work. We can update the sampler doc too so it describes it. I guess it would be the average rate of "new" particles. This makes sense to me

**Comment by gjcooper** [comment]
Closed by commit https://github.com/NewcastleCL/pmwg/commit/a38ad547c8e93695141af2ce3fefde1a1441248b
