### ISSUE TITLE
Update URL references newcastlecl.github.io

### ISSUE THREAD

**Issue by hungodinh** [gjcooper/samplers#62]
Update existing code/content that references https://newcastlecl.github.io/

https://github.com/university-of-newcastle-research/pmwg/blob/c7f25678ef71549919978e56aa84252eb6bc3927/R/pmwg-package.R#L11

https://github.com/university-of-newcastle-research/pmwg/blob/c7f25678ef71549919978e56aa84252eb6bc3927/DESCRIPTION#L21

https://github.com/university-of-newcastle-research/pmwg/blob/c7f25678ef71549919978e56aa84252eb6bc3927/_pkgdown.yml#L27

https://github.com/university-of-newcastle-research/pmwg/blob/c7f25678ef71549919978e56aa84252eb6bc3927/vignettes/pmwg.Rmd#L38

**Comment by gjcooper** [comment]
Closed by 19d8066, 3d66646, 91f90a4 and 0ab0c4d.

All old references to NewcastleCL should be gone.
